name: Build and Package

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Publish Windows executable
        run: dotnet publish Project1.Desktop/Project1.Desktop.csproj -c Release -r win-x64 -o ./publish/windows

      - name: Publish Linux executable
        run: dotnet publish Project1.Desktop/Project1.Desktop.csproj -c Release -r linux-x64 -o ./publish/linux

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Project1
          path: ./publish