name: Build and Package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: "9.0.x"

    - name: Restore dependencies
      run: dotnet restore Project1.sln

    - name: Build solution
      run: dotnet build Project1.sln --configuration Release --no-restore

    - name: Publish executable (Windows)
      if: matrix.os == 'windows-latest'
      run: dotnet publish Project1.Desktop/Project1.Desktop.csproj -c Release -r win-x64 --self-contained true -o ./publish

    - name: Publish executable (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: dotnet publish Project1.Desktop/Project1.Desktop.csproj -c Release -r linux-x64 --self-contained true -o ./publish

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Project1-${{ matrix.os }}
        path: ./publish
